version: '3.8'

services:

  db:
    image: postgres
    restart: always
    container_name: container_postgres
    hostname: hostpostgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty12345
      POSTGRES_DB: ActivitiesDB  